on:
  push:
    branches:
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: |
        npm ci
        npx ts-node-script ./index.ts
      working-directory: ./script
    - run: |
        git add -A
        git commit -m "Updating GHES workflows"
    - run: git push